### ISSUE TITLE
JD-GUI cannot be included in this project

### ISSUE THREAD

**Issue by samczsun** [helios-decompiler/standalone-app#2]
JD-GUI/JD-Core is licensed under the GPLv3 license. This project is licensed under the Apache 2.0 license. Therefore, it is impossible for the JD-Core project to be included in this one.

Please do not ask if I can include it. It's not a matter of whether I am able to, but whether I am allowed to.

If you are able to get in contact with the author of JD-GUI/JD-Core (@emmanue1), please consider asking whether a exception to the GPLv3 may be granted for this project.

**Comment by Storyyeller** [comment]
If you use it from the commandline, I think it could be included for similar reasons to Krakatau.

**Comment by samczsun** [comment]
JD-GUI doesn't appear to have a CLI, and I try to avoid unnecessary writing to disk. With some obfuscated classes Windows doesn't like it (eg reserved names like con and disallowed characters like ").

My solution was to include parts of JD-GUI and manually call JD-Core. However, this approach would not be legal.

I will look into a commandline wrapper for JD-GUI. https://github.com/nviennot/jd-core-java/ looks promising.

**Comment by null-dev** [comment]
I can confirm https://github.com/nviennot/jd-core-java/ works well as I've used it in a couple of my projects. I propose that since you cannot include JD, download the jd-core-java JAR file at runtime from a server you host (or clone the repo and compile it) and call it via command line or load the JAR dynamically into the program.

P.S. From my experience, it also prints many, many exceptions into standard output when it fails to decompile a class.

**Comment by theuserbl** [comment]
The problem is, that JD-GUI is licensed under the GPLv3 and SWT is licensed under the EPL.

If you would change the SWT part with Swing, then there is no problem.
APLv2 and GPLv3 are compatible!

If your program is licensed under the APLv2 and it using a library, which is under the GPLv3, then the whole project is called as "GPLv3 licensed". But your own code remains still under the APLv2.

At
http://www.apache.org/licenses/GPL-compatibility.html

> Apache 2 software can therefore be included in GPLv3 projects, because the GPLv3 license accepts our software into GPLv3 works. However, GPLv3 software cannot be included in Apache projects. The licenses are incompatible in one direction only, and it is a result of ASF's licensing philosophy and the GPLv3 authors' interpretation of copyright law.
>
> This licensing incompatibility applies only when some Apache project software becomes a derivative work of some GPLv3 software, because then the Apache software would have to be distributed under GPLv3. This would be incompatible with ASF's requirement that all Apache software must be distributed under the Apache License 2.0.

1. that APLv2 Helios using a little part GPLv3 code (the JD-Core part) or saying that GPLv3 Helios using a huge part APLv2 code (your part), is only a definition. But the first one is not allowed and the second one is. So say, that Helios is a GPLv3 program, where all other sources, then JD-Core are licensed unter the APLv2. :-)
2. I am not sure, if an Helios, which using the JD-Core, is a derivative work of JD-Core. It makes only use of that library. But it is not a modified or changed version of that library.

Only GPLv3 and EPL are not compatible to each other.

**Comment by samczsun** [comment]
I would be directly invoking methods within JD-Core, which is a big no-no by my understanding. The only reason I've packaged Krakatau is because I'm invoking that over the OS via Runtime which should be safe.

I could license this under the GPL, but I'm not too big a fan of the GPL hence why I'm going through the trouble of worrying about all this. Fortunately, JD-Core doesn't provide any special features (like Krakatau) so I'm not losing too much sleep over it. That's not to say I wouldn't like to include it for completeness.

As for SWT, I'm not seeing that going away anytime soon. Sorry, but it provides a much more user-friendly GUI (as in, it behaves like most programs people use written in C of whatever)

**Comment by emmanue1** [comment]
@samczsun, I send you a response this weekend. @theuserbl, thanks for your alert.

**Comment by samczsun** [comment]
@emmanue1 Ping

**Comment by theuserbl** [comment]
@samczsun emmanue1 have a very looooonnng weekend.

**Comment by samczsun** [comment]
So it appears

**Comment by Janmm14** [comment]
Including JD-Gui in its current state might not be neccessary at all due to various bugs in the decompiler.

**Comment by samczsun** [comment]
Irrelevant at this point due to
1) The lack of maintainence on JD-GUI
2) The number of bugs in it
3) The fact that transformers are being migrated out to a separate project
